POST https://localhost:7020/api/users/login
Content-Type: application/json
{
  "email": "rafael.ferreira.anacleto@gmail.com",
  "password": "Alice@2024!"
}

###
GET https://localhost:7020/api/categorias
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InJhZmFlbC5mZXJyZWlyYS5hbmFjbGV0b0BnbWFpbC5jb20iLCJtYWNvcmF0dGkiOiJodHRwczovL3d3dy5tYWNvcmF0dGkubmV0IiwiYXVkIjoiTWFjb3JhdHRpX0F1ZGllbmNlIiwiaXNzIjoiTWFjb3JhdHRpX0lzc3VlciIsImp0aSI6Ijg3MWJiYWViLTMzYmUtNDhlNC04ZTMyLTc1Y2M1OGY0NjM1NCIsImV4cCI6MTcxMjE1NDM1Nn0.PBNq1m2DpDY5xPDJi8CaRju4jJ1mUsOjuqsC-uVSOQ8